version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:14.18

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "client/package.json" }}
            - v1-dependencies-

      # Install dependencies for client and employee projects
      - run:
          name: Install Dependencies
          command: |
            cd client && npm install
            cd ../employee && npm install

      - save_cache:
          paths:
            - client/node_modules
            - employee/node_modules
          key: v1-dependencies-{{ checksum "client/package.json" }}

      # Install SonarQube Scanner locally in each directory
      - run:
          name: Install SonarScanner Locally
          command: |
            cd client && npm install sonarqube-scanner
            cd ../employee && npm install sonarqube-scanner

      # Run SonarQube Scan from the root directory to include both client and employee
      - run:
          name: Run SonarCloud Scan
          command: |
            npx sonar-scanner \
              -Dsonar.projectKey=MarcoMeyer1_apds-part-2 \
              -Dsonar.organization=marcomeyer1 \
              -Dsonar.sources=client,employee \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.token=$SONAR_TOKEN \
              -X

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
