version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:18-browsers  # Updated valid Docker image

    steps:
      - checkout  # Checkout your code from the repo

      # Cache node_modules to speed up subsequent builds
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "client/package.json" }}
            - v1-dependencies-

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            cd client
            npm install

      # Save node_modules cache
      - save_cache:
          paths:
            - client/node_modules
          key: v1-dependencies-{{ checksum "client/package.json" }}

      # Install SonarScanner locally
      - run:
          name: Install SonarScanner Locally
          command: |
            cd client
            npm install sonarqube-scanner

      # Run SonarQube Scan using SonarCloud with token only
      - run:
          name: Run SonarCloud Scan
          command: |
            cd client
            npx sonar-scanner \
              -Dsonar.projectKey=MarcoMeyer1_apds-part-2 \
              -Dsonar.organization=marcomeyer1 \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.token=7f7c83654f1053d075406d09d3b2eae89326822d

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
