version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:14  # Use Node.js Docker image for your environment
    steps:
      - checkout  # Checkout your code from the repo

      # Cache node_modules to speed up subsequent builds
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests
      - run:
          name: Run Tests
          command: npm test

      # Lint the code
      - run:
          name: Run Lint
          command: npm run lint

      # Run security audit
      - run:
          name: Run NPM Audit
          command: npm audit

   

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
